### ISSUE TITLE
Don't collapse multiple names into a single entry

### ISSUE THREAD

**Issue by mohkale** [twlz0ne/nerd-fonts.el#2]
For example 

```lisp
("fa-files-o fa-copy" . "")
("fa-link fa-chain" . "")
```
I've adapted the data definitions from this package so I can use them with all-the-icons but having multiple names in a single entry is messing up my translations (from all-the-icons glyphs to nerd-fonts glyphs).

I'd much prefer:

```lisp
("fa-files-o" . "")
("fa-copy" . "")
("fa-link" . "")
("fa-chain" . "")
```

**Comment by mohkale** [comment]
Ping @twlz0ne.

**Comment by twlz0ne** [comment]
Sorry for taking so long to reply.
